"""initial tables

Revision ID: 8a2801590734
Revises: 
Create Date: 2026-04-06 17:25:31.417376

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8a2801590734'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('filings',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('accession_number', sa.String(), nullable=False),
    sa.Column('filing_date', sa.DateTime(), nullable=False),
    sa.Column('issuer_name', sa.String(), nullable=False),
    sa.Column('issuer_ticker', sa.String(), nullable=False),
    sa.Column('issuer_cik', sa.String(), nullable=False),
    sa.Column('insider_name', sa.String(), nullable=False),
    sa.Column('insider_title', sa.String(), nullable=False),
    sa.Column('transaction_code', sa.Enum('P', 'S', 'M', 'A', 'G', name='transactioncode'), nullable=False),
    sa.Column('shares_traded', sa.Numeric(), nullable=False),
    sa.Column('price_per_share', sa.Numeric(), nullable=False),
    sa.Column('total_value', sa.Numeric(), nullable=False),
    sa.Column('shares_owned_after', sa.Numeric(), nullable=False),
    sa.Column('is_10b5_1', sa.Boolean(), nullable=False),
    sa.Column('signal_strength', sa.Enum('HIGH', 'MEDIUM', 'LOW', 'NOISE', name='signalstrength'), nullable=True),
    sa.Column('classification', sa.Enum('voluntary_purchase', 'option_exercise', 'planned_sale', 'tax_disposition', 'gift', 'other', name='transactionclassification'), nullable=True),
    sa.Column('classification_reasoning', sa.String(), nullable=True),
    sa.Column('enriched', sa.Boolean(), nullable=False),
    sa.Column('summary', sa.String(), nullable=True),
    sa.Column('chromadb_collection', sa.String(), nullable=True),
    sa.Column('pipeline_status', sa.Enum('INGESTED', 'CLASSIFIED', 'ENRICHED', 'NOTIFIED', 'DONE', name='pipelinestatus'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('accession_number')
    )
    op.create_index(op.f('ix_filings_id'), 'filings', ['id'], unique=False)
    op.create_table('insider_profiles',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('insider_name', sa.String(), nullable=False),
    sa.Column('issuer_cik', sa.String(), nullable=False),
    sa.Column('total_filings', sa.Integer(), nullable=False),
    sa.Column('last_purchase_date', sa.Date(), nullable=True),
    sa.Column('last_sale_date', sa.Date(), nullable=True),
    sa.Column('purchase_count_12m', sa.Integer(), nullable=False),
    sa.Column('sale_count_12m', sa.Integer(), nullable=False),
    sa.Column('largest_transaction_value', sa.Numeric(), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_insider_profiles_id'), 'insider_profiles', ['id'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('telegram_chat_id', sa.BigInteger(), nullable=False),
    sa.Column('username', sa.String(), nullable=True),
    sa.Column('watchlist', sa.JSON(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('telegram_chat_id')
    )
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_insider_profiles_id'), table_name='insider_profiles')
    op.drop_table('insider_profiles')
    op.drop_index(op.f('ix_filings_id'), table_name='filings')
    op.drop_table('filings')
    # ### end Alembic commands ###
